name: run-cpu-unitest 
description: 'run cpu unitest'
runs:
  using: 'docker'
  image: 'ccr.ccs.tencentyun.com/mmspr/turbo_transformers:test-release'
  entrypoint: 'bash github/workspace/entrypoint.sh'
